spring.boot:
    admin.url: http://localhost:8080

management:
    security.enabled: false

app:

    rabbitmq:
        host: localhost
        port: 32775
        username: guest
        password: guest